services:
  - type: web
    name: youtube-insights-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: DB_HOST
        value: database-2.cdays88sihow.eu-north-1.rds.amazonaws.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: database-2
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: Hridaan0711
      - key: JWT_SECRET
        value: dd632...
      - key: GOOGLE_CLIENT_ID
        value: 20603...
      - key: GOOGLE_CLIENT_SECRET
        value: GOCSPX...
      - key: RAPIDAPI_KEY
        value: 04442...
      - key: RAPIDAPI_HOST
        value: youtube138.p.rapidapi.com
